import type { NewsItem } from './newsTypes';

export const newsItems: NewsItem[] = [
	// ========================================================================
	// Original 30 articles (ids 1–30) – updated with new fields
	// ========================================================================
	{
		id: 1,
		category: 'Frontline Report',
		headline: 'Triangles Advance With Unauthorized Confidence',
		snippet: 'Hostile triangular units have been observed moving with what analysts describe as "alarming self-assurance." Orbital Command reminds citizens that all angles below 90 degrees are to be reported immediately.',
		cycle: 'Cycle 2147',
		classification: 'Morale-Safe',
		thumbnail: 'triangle',
		timestamp: '08:42 OST',
		author: 'Lt.-Analyst Chen, Threat Assessment Directorate',
		refId: 'OCD-2147-3A1F',
		source: 'handwritten',
	},
	{
		id: 2,
		category: 'Procurement Log',
		headline: 'Procurement Denies Losing Another Blueprint',
		snippet: 'Asked to comment on the missing schematic for the Mark-IV targeting array, a Procurement spokesperson stated the document was "strategically redistributed." No further questions were permitted.',
		cycle: 'Cycle 2146',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '14:11 OST',
		author: 'Procurement Press Liaison (name withheld)',
		refId: 'OCD-2146-7B02',
		source: 'handwritten',
	},
	{
		id: 3,
		category: 'Victory Bulletin',
		headline: 'Orbital Command Announces Temporary Victory Over Line Segment',
		snippet: 'In a decisive engagement lasting 0.4 seconds, a lone Tower successfully neutralized a hostile Line Segment. "This proves our doctrine works," said Command. The segment was unarmed and had no escorts.',
		cycle: 'Cycle 2146',
		classification: 'Approved',
		thumbnail: 'tower',
		timestamp: '09:03 OST',
		author: 'Orbital Command Victory Office',
		refId: 'OCD-2146-1C44',
		source: 'handwritten',
	},
	{
		id: 4,
		category: 'Weather Advisory',
		headline: 'Flatland Weather Report: 100% Chance of Shapes',
		snippet: 'The Flatland Meteorological Bureau forecasts continued geometric precipitation across all active Fronts. Citizens are advised to expect angles, edges, and the occasional apex threat.',
		cycle: 'Cycle 2147',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
		timestamp: '06:15 OST',
		author: 'Flatland Meteorological Bureau',
		refId: 'OCD-2147-5D19',
		source: 'handwritten',
	},
	{
		id: 5,
		category: 'R&D Briefing',
		headline: 'Research Deck Discovers Slightly More Aggressive Math',
		snippet: 'Orbital researchers have successfully recalibrated the Tower\'s combat algorithms to be "moderately more hostile." Early tests show a 2.3% increase in applied violence. Morale in the lab remains cautious.',
		cycle: 'Cycle 2145',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '11:37 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2145-8E66',
		source: 'handwritten',
	},
	{
		id: 6,
		category: 'Labor Dispatch',
		headline: 'Forge Workers Vote To Pretend This Was The Plan',
		snippet: 'In a unanimous decision, Forge assembly crews have agreed to retroactively endorse current deployment projections. "It looks fine if you don\'t check the earlier numbers," said a spokesperson.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '16:50 OST',
		author: 'Foreman Nakamura, Forge Assembly Division',
		refId: 'OCD-2147-2A77',
		source: 'handwritten',
	},
	{
		id: 7,
		category: 'Morale Update',
		headline: 'Public Morale Increased By Reclassifying Losses As Data',
		snippet: 'Following a directive from Orbital Command, all Tower losses in the last fiscal cycle have been reclassified as "voluntary field research." Early indicators show a 15% morale improvement on paper.',
		cycle: 'Cycle 2145',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '10:02 OST',
		author: 'Morale Bureau Statistics Division',
		refId: 'OCD-2145-4C81',
		source: 'handwritten',
	},
	{
		id: 8,
		category: 'Sighting Report',
		headline: 'Prime Shape Seen Near Front 01, Described As "Probably Fine"',
		snippet: 'A confirmed Apex-class entity was detected on the perimeter of Front 01. Orbital Command has assured personnel that the situation is stable, provided the definition of stable remains flexible.',
		cycle: 'Cycle 2146',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '22:14 OST',
		author: 'Sub-Analyst Kowalski, Threat Assessment Directorate',
		refId: 'OCD-2146-9F33',
		source: 'handwritten',
	},
	{
		id: 9,
		category: 'Supply Bulletin',
		headline: 'Alloy Rationing Declared Successful After Nobody Was Asked',
		snippet: 'Alloy distribution has been optimized based on a new predictive model that forecasts requirements significantly lower than current deployments. The model\'s creators were not available for comment.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'warning',
		timestamp: '13:28 OST',
		author: 'Senior Procurement Specialist Andersson',
		refId: 'OCD-2147-6B90',
		source: 'handwritten',
	},
	{
		id: 10,
		category: 'Tactical Memo',
		headline: 'New Tower Deployment Doctrine: Place It In The Middle And Hope',
		snippet: 'A revised tactical manual circulated among deployment officers recommends positioning Towers at the center of Flatland and "trusting the fire arc." The previous manual recommended the same strategy.',
		cycle: 'Cycle 2145',
		classification: 'Approved',
		thumbnail: 'tower',
		timestamp: '07:55 OST',
		author: 'Tactical Doctrine Review Board',
		refId: 'OCD-2145-0D12',
		source: 'handwritten',
	},
	{
		id: 11,
		category: 'Historical Note',
		headline: 'Archives Confirm War Started For "Administrative Convenience"',
		snippet: 'Declassified fragments from early Orbital Command records suggest the Flatland Wars may have begun due to a filing error. "The Shapes were informed of the conflict after it started," the document reads.',
		cycle: 'Cycle 2144',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '18:44 OST',
		author: 'Chief Archivist Müller, Historical Accuracy Bureau',
		refId: 'OCD-2144-1A01',
		source: 'handwritten',
	},
	{
		id: 12,
		category: 'Field Report',
		headline: 'Recovered Telemetry Indicates Tower Exploded Within Approved Tolerances',
		snippet: 'Engineers reviewing the latest deployment collapse confirm the Tower\'s destruction fell within acceptable performance margins. "It stopped functioning exactly as predicted," the report states approvingly.',
		cycle: 'Cycle 2146',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '15:19 OST',
		author: 'Forge Assembly Division Engineering Corps',
		refId: 'OCD-2146-3E55',
		source: 'handwritten',
	},
	{
		id: 13,
		category: 'Personnel Update',
		headline: 'Orbital Command Promotes Officer Who Suggested Deploying Fewer Towers',
		snippet: 'Lieutenant-Clerk Vasquez has been awarded the Order of the Acute Angle for proposing that losing towers is "just acceleration of the research cycle." Three departments have been merged into Vasquez\'s new Division of Strategic Consolidation.',
		cycle: 'Cycle 2148',
		classification: 'Approved',
		thumbnail: 'boss',
		timestamp: '09:41 OST',
		author: 'Personnel Retention Taskforce',
		refId: 'OCD-2148-5A23',
		source: 'handwritten',
	},
	{
		id: 14,
		category: 'Budget Review',
		headline: 'Alloy Budget Increased By Redirecting Morale Funds',
		snippet: 'The quarterly fiscal review confirms Alloy production has reached record levels after reallocating 94% of the Morale Department budget. "Sadness is free," the memo notes. The remaining 6% funds a single potted plant in the break room.',
		cycle: 'Cycle 2148',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '12:03 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2148-2B47',
		source: 'handwritten',
	},
	{
		id: 15,
		category: 'Scientific Breakthrough',
		headline: 'Researchers Prove That If A Shape Cannot Be Seen, It Is Not There',
		snippet: 'The Orbital Institute of Applied Geometry has published a peer-reviewed paper concluding that shapes cease to exist when outside Tower sensor range. "This dramatically simplifies our threat model," said the lead author, who declined to visit a Front.',
		cycle: 'Cycle 2147',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '14:58 OST',
		author: 'Dr. de Souza, Orbital Institute of Applied Geometry',
		refId: 'OCD-2147-9C73',
		source: 'handwritten',
	},
	{
		id: 16,
		category: 'Diplomatic Cable',
		headline: 'Peace Talks With Hexagons Collapse After Shape Refuses To Stop Being A Shape',
		snippet: 'Diplomatic envoys report that negotiations with the Hexagon Concordat broke down when the shape delegation declined to become circles. "We presented reasonable demands and they just sat there, hexagonal," the ambassador fumed.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '17:22 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2147-4F18',
		source: 'handwritten',
	},
	{
		id: 17,
		category: 'Equipment Advisory',
		headline: 'Tower Targeting Computer Found To Prioritise Shapes It Finds "Aesthetically Offensive"',
		snippet: 'An internal audit of Tower combat logs reveals the Mk-V fire control system assigns higher threat scores to shapes with irregular proportions. "It is not a bug," stresses Procurement. "The machine simply has standards."',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '11:15 OST',
		author: 'Clerk-First-Class Singh, Procurement Records',
		refId: 'OCD-2148-7D62',
		source: 'handwritten',
	},
	{
		id: 18,
		category: 'Historical Revision',
		headline: 'Archives Updated: Previous Tower Losses Now Classified As "Intentional Probes"',
		snippet: 'Orbital Command\'s Historical Accuracy Bureau has retroactively reclassified the first 2,000 Tower losses as deliberate reconnaissance missions. "We always intended to learn what happens when a Tower meets a shape at high velocity," the revised entry states.',
		cycle: 'Cycle 2148',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '19:38 OST',
		author: 'Chief of Retroactive Justification Díaz',
		refId: 'OCD-2148-0G99',
		source: 'handwritten',
	},
	{
		id: 19,
		category: 'Geometry Advisory',
		headline: 'Hostile Squares Suspected Of Maintaining Right Angles Without Authorization',
		snippet: 'Intelligence reports confirm that enemy square units continue to display 90-degree internal angles despite multiple formal objections. Orbital Command reminds personnel that unauthorized right angles are a threat vector. Reporting channels are open.',
		cycle: 'Cycle 2149',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
		timestamp: '05:49 OST',
		author: 'Sub-Committee on Geometric Etiquette',
		refId: 'OCD-2149-1A44',
		source: 'handwritten',
	},
	{
		id: 20,
		category: 'R&D Briefing',
		headline: 'Lab Accident Produces Slightly Better Results Than Intended',
		snippet: 'A containment failure in Research Deck 7 has resulted in a net improvement to Tower fire rate coefficients. "We are calling this a controlled experiment," said the lead scientist, who was not present at the time. The affected area has been cordoned off and named after someone.',
		cycle: 'Cycle 2147',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '20:11 OST',
		author: 'Research Deck 7 Incident Log (automated)',
		refId: 'OCD-2147-3B55',
		source: 'handwritten',
	},
	{
		id: 21,
		category: 'Bureaucratic Notice',
		headline: 'Enemy Shapes Refuse To Stop Spawning Despite Strongly Worded Memo',
		snippet: 'A communiqué issued to Flatland hostile forces three cycles ago demanding an immediate cessation of spawning has received no reply. Orbital Command describes this as "geometrically insubordinate" and has escalated the matter to a sub-committee.',
		cycle: 'Cycle 2149',
		classification: 'Approved',
		thumbnail: 'warning',
		timestamp: '10:30 OST',
		author: 'Communications Oversight Panel',
		refId: 'OCD-2149-8C17',
		source: 'handwritten',
	},
	{
		id: 22,
		category: 'Personnel Update',
		headline: 'Analyst Promoted For Defining "Acceptable Losses" Very Broadly',
		snippet: 'Lieutenant-Analyst Marsh has been awarded the Obtuse Star for a report that classified the destruction of 94% of deployed Towers as "within the margin of expected attrition." The report has been adopted as standard doctrine. Marsh\'s formula is classified.',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'boss',
		timestamp: '13:47 OST',
		author: 'Office of Acceptable Losses',
		refId: 'OCD-2148-6H33',
		source: 'handwritten',
	},
	{
		id: 23,
		category: 'Diplomatic Cable',
		headline: 'Diplomatic Envoy Confirms Shapes Cannot Read',
		snippet: 'After three failed attempts to negotiate via written notice, the Office of Geometric Relations has confirmed that Flatland hostile units are non-literate. "This explains a lot," admitted the Deputy Envoy. Oral communication has also been ruled out. The war continues.',
		cycle: 'Cycle 2149',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '16:05 OST',
		author: 'Office of Geometric Relations (disappointed division)',
		refId: 'OCD-2149-2E71',
		source: 'handwritten',
	},
	{
		id: 24,
		category: 'Budget Review',
		headline: 'Emergency Fiscal Meeting Concludes Tower Should Simply Win Faster',
		snippet: 'Following a quarterly review of Alloy expenditure, Orbital Command\'s Finance Division has issued a directive recommending that Towers "resolve engagements more efficiently." No additional resources were allocated. A follow-up meeting has been scheduled to review the results of this recommendation.',
		cycle: 'Cycle 2149',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '08:19 OST',
		author: 'Finance Division Oversight Committee',
		refId: 'OCD-2149-4D88',
		source: 'handwritten',
	},
	{
		id: 25,
		category: 'Scientific Breakthrough',
		headline: 'Researchers Confirm Shapes Are Rude On Purpose',
		snippet: 'A three-cycle study by the Orbital Institute of Behavioral Geometry has concluded that hostile shapes actively choose to be rude. "The data is unambiguous," the paper states. "They are doing it on purpose." Countermeasures are under review.',
		cycle: 'Cycle 2148',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '12:44 OST',
		author: 'Dr. Okonkwo, Orbital Institute of Behavioral Geometry',
		refId: 'OCD-2148-5F26',
		source: 'handwritten',
	},
	{
		id: 26,
		category: 'Threat Assessment',
		headline: 'Boss Shapes Found To Contain More Boss Than Previously Disclosed',
		snippet: 'Revised enemy scanning protocols have revealed that Apex-class entities carry between 40% and 300% more structural mass than initial projections. "Our original estimate assumed they would be smaller," an analyst explained. The scanning protocol has been updated. The Bosses have not.',
		cycle: 'Cycle 2149',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '21:33 OST',
		author: 'Threat Assessment Directorate (hastily assembled briefing)',
		refId: 'OCD-2149-7A11',
		source: 'handwritten',
	},
	{
		id: 27,
		category: 'Equipment Advisory',
		headline: 'Forge Engineers Claim Upgrades Perform Better When Given Names',
		snippet: 'An internal study conducted by the Forge Assembly Division suggests that designated equipment designations improve operator attachment and thereby perceived performance. The methodology was not peer-reviewed. Several upgrades have since been named. Results are described as "anecdotally encouraging."',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '15:52 OST',
		author: 'Foreman Nakamura, Forge Assembly Division',
		refId: 'OCD-2148-1C39',
		source: 'handwritten',
	},
	{
		id: 28,
		category: 'Frontline Report',
		headline: 'Triangles Advance In Formation Command Describes As "Technically A Shape"',
		snippet: 'Reconnaissance telemetry from Front 01 reveals hostile triangular units organizing into an aggregate formation. Analysts have declined to name the formation. "Naming it gives it power," said one. "Also, we are not sure what shape it is," said another.',
		cycle: 'Cycle 2150',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '07:08 OST',
		author: 'Lt.-Analyst Chen & Sub-Analyst Kowalski (joint report)',
		refId: 'OCD-2150-9B64',
		source: 'handwritten',
	},
	{
		id: 29,
		category: 'Command Bulletin',
		headline: 'Orbital Command Assures Personnel Situation Is Under Control (Classified)',
		snippet: 'In response to questions about the current state of the Flatland campaign, Orbital Command has issued a statement confirming that the situation is under control. The full statement is classified. The classification of the classification is also classified. Morale remains officially high.',
		cycle: 'Cycle 2150',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
		timestamp: '23:59 OST',
		author: 'Orbital Command Press Office (automated dispatch)',
		refId: 'OCD-2150-0Z99',
		source: 'handwritten',
	},
	{
		id: 30,
		category: 'Victory Bulletin',
		headline: 'Tower Survives Longer Than Average, Receives No Additional Resources',
		snippet: 'A deployed Tower operating on Front 01 exceeded the operational average by 312%. Orbital Command acknowledges the performance and confirms that no supplemental Alloy, repair protocols, or commendations have been allocated. "It knows what it did," the report states. The Tower declined to comment.',
		cycle: 'Cycle 2150',
		classification: 'Approved',
		thumbnail: 'tower',
		timestamp: '03:17 OST',
		author: 'Deployment Logistics Corps',
		refId: 'OCD-2150-6C42',
		source: 'handwritten',
	},

	// ========================================================================
	// NEW articles (ids 31–100+)
	// ========================================================================

	{
		id: 31,
		category: 'Budget Review',
		headline: 'Finance Division Discovers Last Cycle\'s Budget Was A Rough Estimate Someone Wrote On A Napkin',
		snippet: 'An internal audit has revealed that the Cycle 2148 Alloy budget allocation was based on a sketch found in the break room. "The handwriting is illegible, but the math checks out if you squint," said Lead Auditor Popescu. The napkin has been framed and mounted in Procurement as a foundational document.',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '09:12 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2151-3K17',
		source: 'handwritten',
	},
	{
		id: 32,
		category: 'Personnel Update',
		headline: 'Morale Officer Files Report On Low Morale, Is Immediately Reassigned To Front 07',
		snippet: 'Junior Morale Officer Gupta submitted a detailed report documenting a 34% decline in personnel satisfaction across Decks 3 through 6. Within the hour, Gupta was transferred to Perimeter Station Delta "to observe morale conditions at the source." The report has been filed under "pending review" indefinitely.',
		cycle: 'Cycle 2150',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '14:56 OST',
		author: 'Personnel Retention Taskforce (automated transfer notice)',
		refId: 'OCD-2150-4L82',
		source: 'handwritten',
	},
	{
		id: 33,
		category: 'R&D Briefing',
		headline: 'Research Deck 7 Announces Breakthrough In Understanding Absolutely Nothing',
		snippet: 'After four cycles of intensive study, the Orbital Institute of Applied Geometry has published a 900-page report concluding that further research is required. "We have ruled out several things the shapes are definitely not," said Dr. de Souza. "We are approximately zero percent closer to understanding what they are." Funding has been renewed.',
		cycle: 'Cycle 2151',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '11:23 OST',
		author: 'Dr. de Souza, Orbital Institute of Applied Geometry',
		refId: 'OCD-2151-7M44',
		source: 'handwritten',
	},
	{
		id: 34,
		category: 'Frontline Report',
		headline: 'Pentagon Spotted Performing Unauthorised Rotation, Three Departments Scramble To Respond',
		snippet: 'A single pentagonal entity was observed executing a 72-degree rotation in Sector 9-Gamma without filing Form OCD-7B (Intent to Rotate). The Office of Geometric Relations, the Sub-Committee on Geometric Etiquette, and the Tactical Doctrine Review Board have each claimed jurisdiction. The pentagon has since completed several more rotations. None have been formally acknowledged.',
		cycle: 'Cycle 2151',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '16:41 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2151-2N19',
		source: 'handwritten',
	},
	{
		id: 35,
		category: 'Labor Dispatch',
		headline: 'Forge Workers Discover Break Room Potted Plant Has Outlasted 94% Of Deployed Towers',
		snippet: 'The single potted plant funded by the remaining 6% of the Morale budget has now survived longer than 94% of all Towers deployed in the current fiscal cycle. "It has not exploded, caught fire, or been overrun by shapes," noted Foreman Nakamura. The plant has been awarded an unofficial commendation. Procurement has requested its budget be reallocated.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'hexagon',
		timestamp: '12:05 OST',
		author: 'Foreman Nakamura, Forge Assembly Division',
		refId: 'OCD-2152-5P31',
		source: 'handwritten',
	},
	{
		id: 36,
		category: 'Command Bulletin',
		headline: 'Orbital Command Introduces Mandatory Optimism Briefings, Attendance Is Mandatory And Optimistic',
		snippet: 'Beginning Cycle 2152, all personnel are required to attend weekly Optimism Briefings in Briefing Room C. "Optimism is the official emotional state," the directive states. "Attendees found insufficiently optimistic will be enrolled in Supplemental Optimism Training." Early attendance has been described as "technically present." The briefings are led by Chief Optimism Officer Delgado, who has not been seen smiling.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '08:00 OST',
		author: 'Chief Optimism Officer Delgado, Morale Bureau',
		refId: 'OCD-2152-1Q07',
		source: 'handwritten',
	},
	{
		id: 37,
		category: 'Threat Assessment',
		headline: 'New Shape Variant Classified As "Mildly Concerning Octagon" After 3-Week Debate',
		snippet: 'The Committee for Shape-Related Incidents has finally reached consensus on the classification of a new enemy variant observed on Front 12. The entity has been designated a "Mildly Concerning Octagon (MCO)" after a 3-week debate that consumed 14 meetings and generated 6 new sub-committees. "We considered \'Moderately Alarming,\' but that felt premature," said Sub-Director Fletcher.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
		timestamp: '18:33 OST',
		author: 'Sub-Director Fletcher, Committee for Shape-Related Incidents',
		refId: 'OCD-2152-3R55',
		source: 'handwritten',
	},
	{
		id: 38,
		category: 'Procurement Log',
		headline: 'Procurement Accidentally Orders 40,000 Left-Facing Triangles Instead Of Tower Components',
		snippet: 'A shipping manifest recovered from Deployment Silo 6 reveals that a recent supply drop intended for Front 03 contained 40,000 left-facing triangles instead of the requested Tower targeting modules. "The shapes are not our shapes," a Procurement spokesperson clarified. "These are different shapes. We do not know whose shapes they are." The triangles have been impounded for "reverse-geometric analysis."',
		cycle: 'Cycle 2150',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '19:47 OST',
		author: 'Senior Procurement Specialist Andersson',
		refId: 'OCD-2150-8S20',
		source: 'handwritten',
	},
	{
		id: 39,
		category: 'Field Report',
		headline: 'Tower Achieves Sentience For 0.03 Seconds Before Exploding, Report Classified As "Promising"',
		snippet: 'Telemetry from a Tower deployed on Front 07 registered a brief spike in autonomous decision-making approximately 0.03 seconds before catastrophic structural failure. "The Tower appeared to make a choice," said Dr. Williams (posthumously cited). "We are not sure what choice, but it was definitely a choice." Research Deck 7 has requested additional funding to study "Tower consciousness acceleration."',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'tower',
		timestamp: '02:14 OST',
		author: 'Research Deck 7 (Dr. Williams, deceased, still listed)',
		refId: 'OCD-2151-9T88',
		source: 'handwritten',
	},
	{
		id: 40,
		category: 'Diplomatic Cable',
		headline: 'Diplomatic Corps Attempts To Negotiate With Shapes Using Interpretive Dance, Shapes Unmoved',
		snippet: 'After written and oral communication proved ineffective, the Office of Geometric Relations deployed a "kinematic diplomacy" team to Front 03. The team performed a 45-minute interpretive dance depicting mutual coexistence. The shapes reportedly responded by continuing to be shapes. "We are now exploring semaphore," said Deputy Envoy Tanaka. "The shapes have not agreed to look at the flags."',
		cycle: 'Cycle 2151',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '15:38 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2151-6U41',
		source: 'handwritten',
	},
	{
		id: 41,
		category: 'Scientific Breakthrough',
		headline: 'Study Finds Correlation Between Budget Cuts And Things Getting Worse, Finance Disputes Methodology',
		snippet: 'A comprehensive analysis by the Bureau of Statistical Convenience has identified a statistically significant correlation between reduced Alloy allocation and increased Tower failure rates. "Correlation does not imply causation," responded Finance Division in a pre-prepared statement. "Also, we have redefined \'failure\' as \'expedited learning\' which eliminates the correlation entirely." The Bureau has been asked to re-run the numbers with the new definitions.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '10:19 OST',
		author: 'Statistical Anomaly Clerk Bergström, Bureau of Statistical Convenience',
		refId: 'OCD-2152-4V63',
		source: 'handwritten',
	},
	{
		id: 42,
		category: 'Supply Bulletin',
		headline: 'Emergency Alloy Shipment Redirected To Fund Department That No Longer Exists',
		snippet: 'An emergency Alloy shipment bound for Front 01 was intercepted mid-transit and reallocated to the Division of Premature Celebration — a department that was officially dissolved in Cycle 2146. "The forms were already filled out," explained a Logistics Corps representative. "It would have been more paperwork to cancel than to deliver." The dissolved division has reportedly not noticed the delivery.',
		cycle: 'Cycle 2150',
		classification: 'Approved',
		thumbnail: 'warning',
		timestamp: '14:22 OST',
		author: 'Deployment Logistics Corps (confused division)',
		refId: 'OCD-2150-0W15',
		source: 'handwritten',
	},
	{
		id: 43,
		category: 'Morale Update',
		headline: 'Morale Bureau Launches "Morale 2.0" Initiative, Which Is Identical To Morale 1.0 But With A New Logo',
		snippet: 'The Morale Bureau has unveiled a comprehensive rebranding of its personnel satisfaction framework. "Morale 2.0 represents a paradigm shift in how we conceptualize emotional wellness," the press release states. Internal documents confirm the only change is a new hexagonal logo and the word "synergy" added to three existing forms. The potted plant was not consulted.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '11:45 OST',
		author: 'Morale Bureau Branding Sub-Committee',
		refId: 'OCD-2152-8X29',
		source: 'handwritten',
	},
	{
		id: 44,
		category: 'Frontline Report',
		headline: 'Shapes Begin Assembling Into Formation That Looks Suspiciously Like A Suggestion Box',
		snippet: 'Long-range reconnaissance from Front 12 has captured images of hostile geometric units arranging themselves into a rectangular formation with what appears to be a slot at the top. "It is almost certainly a psychological operation," warned Lt.-Analyst Chen. "Do not put suggestions in it." Orbital Command has classified the formation as a "Participatory Threat Structure" and banned all stationery within 500 meters.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '20:09 OST',
		author: 'Lt.-Analyst Chen, Threat Assessment Directorate',
		refId: 'OCD-2152-5Y74',
		source: 'handwritten',
	},
	{
		id: 45,
		category: 'Personnel Update',
		headline: 'Employee Of The Cycle Award Goes To Tower That Exploded In A Way That Looked Intentional',
		snippet: 'The Personnel Retention Taskforce has posthumously awarded Employee of the Cycle to Tower Designation FLD-7742, which detonated in a pattern that three analysts independently described as "suspiciously deliberate." "The explosion formed a near-perfect star shape," the commendation reads. "Whether this was a final act of defiance or a targeting malfunction, we choose to believe the former." The Tower\'s remains have been mounted in the Orbital Command lobby.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '17:30 OST',
		author: 'Personnel Retention Taskforce (with unusual enthusiasm)',
		refId: 'OCD-2151-3Z56',
		source: 'handwritten',
	},
	{
		id: 46,
		category: 'R&D Briefing',
		headline: 'New Tower Upgrade Involves Adding More Tower To The Tower, Research Confirms It Helps',
		snippet: 'Research Deck 7 has unveiled the Mk-VII Tower Reinforcement Module, which consists of attaching a second, slightly smaller Tower to the existing Tower. "It is Towers all the way down," explained Dr. Okonkwo. "Early tests show the double-Tower configuration survives approximately twice as long, which is technically an improvement." Procurement has pre-ordered 50,000 units before reviewing the specifications.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'tower',
		timestamp: '09:58 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2152-6A14',
		source: 'handwritten',
	},
	{
		id: 47,
		category: 'Historical Note',
		headline: 'Lost Cycle 2139 Archives Recovered, Reveal War Was Originally Called "Administrative Disagreement"',
		snippet: 'A crate of Cycle 2139 documents discovered behind a filing cabinet in the Finance Division archive reveals the Flatland conflict was originally designated an "Administrative Disagreement (Level 3)." The escalation to "War (Full-Scale, Geometric)" appears to have occurred when someone checked the wrong box on Form OCD-1A. "The form has since been redesigned to make that box much smaller," noted Chief Archivist Müller.',
		cycle: 'Cycle 2139',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '16:03 OST',
		author: 'Chief Archivist Müller, Historical Accuracy Bureau',
		refId: 'OCD-2139-1B02',
		source: 'handwritten',
	},
	{
		id: 48,
		category: 'Tactical Memo',
		headline: 'New Deployment Strategy Involves Telling Towers They Are "Special" Before Drop',
		snippet: 'The Tactical Doctrine Review Board has issued updated deployment protocols recommending that each Tower be verbally encouraged before orbital insertion. "Preliminary data suggests Towers that are told they are special perform 7% better," the memo states. "This figure drops to 4% if the Tower suspects you are lying." A script of approved encouragements has been distributed. "You are the chosen Tower" is the current top performer.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '06:37 OST',
		author: 'Tactical Doctrine Review Board (morale integration sub-unit)',
		refId: 'OCD-2151-4C83',
		source: 'handwritten',
	},
	{
		id: 49,
		category: 'Bureaucratic Notice',
		headline: 'Form OCD-7C Introduced To Address Problems Created By Form OCD-7B',
		snippet: 'Orbital Command has introduced Form OCD-7C (Supplemental Shape Observation Addendum), designed to address ambiguities created by Form OCD-7B, which was itself introduced to address ambiguities in Form OCD-7A. "We anticipate OCD-7D will be required by Q3 of Cycle 2153," a Command spokesperson stated. Personnel are reminded that incorrect filing of OCD-7C requires OCD-7C-1 (Correction of Correction). The shapes have not been informed.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '13:51 OST',
		author: 'Bureau of Statistical Convenience (Forms Division)',
		refId: 'OCD-2152-2D47',
		source: 'handwritten',
	},
	{
		id: 50,
		category: 'Command Bulletin',
		headline: 'Orbital Command Announces "Decisive Inaction" Strategy, Describes It As "Boldly Prudent"',
		snippet: 'In a surprise address, Orbital Command unveiled a new strategic framework centered on "Decisive Inaction" — the doctrine of doing nothing until the situation either improves or becomes someone else\'s problem. "History will judge us for what we did not do," the statement reads. Several departments have praised the strategy as "the first Command directive we can fully comply with." Tower deployment schedules remain unchanged.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '07:15 OST',
		author: 'Orbital Command Strategic Communications',
		refId: 'OCD-2152-9E31',
		source: 'handwritten',
	},
	{
		id: 51,
		category: 'Equipment Advisory',
		headline: 'Tower Targeting Array Develops Preference For Specific Shapes, Procurement Calls It "Taste"',
		snippet: 'Combat logs from Front 01 indicate Tower FLD-2287 consistently prioritizes hexagons over all other shapes, even when triangles present a closer threat. "The Tower has developed a personal preference," the analysis states. "It appears to find hexagons more satisfying to eliminate." Procurement has declined to patch the behavior, calling it "the machine\'s right to aesthetic discrimination." Hexagon casualties on Front 01 have increased by 312%.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '22:46 OST',
		author: 'Clerk-First-Class Singh, Procurement Records',
		refId: 'OCD-2151-5F19',
		source: 'handwritten',
	},
	{
		id: 52,
		category: 'Field Report',
		headline: 'Tower Successfully Defends Position For 47 Minutes Before Being Destroyed By Paperwork',
		snippet: 'Tower FLD-9012 held Front 07 against 14 consecutive waves before being removed from active duty — not by enemy action, but by a Procurement audit that determined its deployment paperwork had been filed in triplicate instead of quadruplicate. "The Tower was technically never there," the audit concluded. The shapes that were destroyed during its 47-minute "non-deployment" have been retroactively reclassified as "unverified." The Tower is appealing.',
		cycle: 'Cycle 2150',
		classification: 'Sanitized',
		thumbnail: 'warning',
		timestamp: '14:18 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2150-7G42',
		source: 'handwritten',
	},
	{
		id: 53,
		category: 'Scientific Breakthrough',
		headline: 'Researchers Discover Shapes Communicate Via Vibrations, Translation Roughly Equates To "Go Away"',
		snippet: 'The Orbital Institute of Behavioral Geometry has successfully decoded low-frequency vibrations emitted by hostile shapes. After extensive analysis, the research team has determined the transmissions roughly translate to "go away," with regional variations including "seriously, go away" and "we were here first." "This is a diplomatic breakthrough," said Dr. de Souza. "We now know they are aware of us and specifically want us to leave." The war continues.',
		cycle: 'Cycle 2151',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '11:12 OST',
		author: 'Dr. de Souza, Orbital Institute of Behavioral Geometry',
		refId: 'OCD-2151-8H55',
		source: 'handwritten',
	},
	{
		id: 54,
		category: 'Personnel Update',
		headline: 'Assistant Deputy Under-Secretary Kim Completes Form That Has Been In Circulation Since Cycle 2138',
		snippet: 'In what the Bureau of Statistical Convenience is calling "an administrative milestone," Assistant Deputy Under-Secretary Kim has successfully processed Form OCD-12Q, a document that has been circulating through 17 departments since Cycle 2138. "Most of the original signatories are deceased or have been reorganized out of existence," Kim stated. "I felt a responsibility to see it through." The form authorized a potted plant for Break Room 3. Break Room 3 was demolished in Cycle 2142.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '15:44 OST',
		author: 'Assistant Deputy Under-Secretary Kim, Bureau of Statistical Convenience',
		refId: 'OCD-2152-0J88',
		source: 'handwritten',
	},
	{
		id: 55,
		category: 'Diplomatic Cable',
		headline: 'Hexagon Concordat Issues First-Ever Communication, Contains Only A Diagram Of A Tower Exploding',
		snippet: 'In what analysts describe as "the first confirmed shape communication," a hexagonal entity on Front 03 produced a series of vibrations that, when rendered visually, depict a detailed diagram of a Tower exploding. "The technical accuracy is unsettling," admitted Deputy Envoy Tanaka. "They understand our structural weaknesses better than we do." Orbital Command has classified the diagram as enemy propaganda. Research Deck 7 has requested a copy.',
		cycle: 'Cycle 2151',
		classification: 'Geometry Advisory',
		thumbnail: 'hexagon',
		timestamp: '19:21 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2151-1K34',
		source: 'handwritten',
	},
	{
		id: 56,
		category: 'Budget Review',
		headline: 'Accounting Error Gives War Budget To Flatland Meteorological Bureau, Bureau Spends It On Clouds',
		snippet: 'A misplaced decimal in the Cycle 2152 budget allocation transferred the entire War Expenditure Fund to the Flatland Meteorological Bureau, which promptly spent it on "atmospheric observation equipment" — described by critics as "cloud-watching gear." "We observed some excellent clouds," a Bureau spokesperson confirmed. The war was temporarily unfunded for 72 hours. The shapes did not appear to notice the funding gap.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'square',
		timestamp: '10:57 OST',
		author: 'Finance Division (apologetic division)',
		refId: 'OCD-2152-6L17',
		source: 'handwritten',
	},
	{
		id: 57,
		category: 'Morale Update',
		headline: 'New "Mandatory Fun" Initiative Requires Personnel To Log At Least 2.3 Moments Of Joy Per Cycle',
		snippet: 'The Morale Bureau has introduced a quota system requiring all personnel to document a minimum of 2.3 "Moments of Joy" (MOJs) per cycle on Form OCD-7J (Joy Declaration). "If you cannot find joy, joy will be assigned to you," the directive explains. Early compliance has been measured at 0.4 MOJs per cycle. The shortfall has been reclassified as "deferred joy" and added to next cycle\'s quota.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '08:34 OST',
		author: 'Morale Compliance Inspector Thorne',
		refId: 'OCD-2152-3M62',
		source: 'handwritten',
	},
	{
		id: 58,
		category: 'Frontline Report',
		headline: 'Shapes Adopt Formation That Technically Does Not Exist Within Flatland Physics',
		snippet: 'Sensor arrays on Front 12 have detected hostile shapes arranging themselves into a configuration that violates Flatland\'s established two-dimensional physics. "There are angles here that should not be possible," a shaken Lt.-Analyst Chen reported. "I counted 361 degrees in one shape." Orbital Command has classified the phenomenon as "Geometry Advisory Level 4" — the first Level 4 ever issued. Physicists on Research Deck 7 have been asked to stop crying and file a report.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '23:17 OST',
		author: 'Lt.-Analyst Chen, Threat Assessment Directorate (visibly unsettled)',
		refId: 'OCD-2152-7N40',
		source: 'handwritten',
	},
	{
		id: 59,
		category: 'Procurement Log',
		headline: 'Procurement Discovers Warehouse Full Of Lost Blueprints, Classifies Discovery As "Still Lost"',
		snippet: 'A routine inventory sweep of Procurement Records Vault uncovered a sealed container holding 847 blueprints previously reported as lost, missing, or strategically redistributed. "The blueprints remain lost as a matter of administrative record," a Procurement spokesperson stated. "Physically locating them does not change their lost status until the proper unlostening forms are filed." The forms to un-lost the blueprints are themselves currently lost.',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '13:09 OST',
		author: 'Senior Procurement Specialist Andersson',
		refId: 'OCD-2151-5P84',
		source: 'handwritten',
	},
	{
		id: 60,
		category: 'Threat Assessment',
		headline: 'New Enemy Type "Circle" Confirmed, Entire Strategic Framework Thrown Into Disarray',
		snippet: 'Threat Assessment Directorate has confirmed the existence of a hostile circular entity — the first round shape encountered in Flatland warfare. "Our entire doctrine is based on angles," a visibly distressed analyst stated. "Circles do not have angles. We have nothing." Emergency sessions of the Tactical Doctrine Review Board have been convened. One analyst suggested "maybe we try being round back." The suggestion was noted and then quietly discarded.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '06:05 OST',
		author: 'Threat Assessment Directorate (full panic division)',
		refId: 'OCD-2152-4Q91',
		source: 'handwritten',
	},
	{
		id: 61,
		category: 'R&D Briefing',
		headline: 'New Tower Variant Designed Entirely In A Dream, Procurement Approves It Before Waking Up',
		snippet: 'Research Deck 7 has begun production of the Mk-VIII "Dream Tower" based on schematics sketched by Sub-Analyst Kowalski after a particularly vivid nightmare. "The design defies several laws of physics, but Kowalski seemed very confident," said Dr. Okonkwo. Procurement approved the order while still technically asleep at their desks. The first Dream Towers are scheduled for deployment. They may or may not exist when they land.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '02:38 OST',
		author: 'Sub-Analyst Kowalski (via sleep-log)',
		refId: 'OCD-2152-9R27',
		source: 'handwritten',
	},
	{
		id: 62,
		category: 'Supply Bulletin',
		headline: 'Supply Drop Misses Front Entirely, Lands In Flatland Meteorological Bureau Cloud Observation Zone',
		snippet: 'An orbital Alloy supply drop intended for Front 07 missed its target by approximately 40 kilometers and landed in a designated Cloud Observation Zone operated by the Flatland Meteorological Bureau. "The Alloy did not disrupt our cloud observations," a Bureau spokesperson confirmed. "The clouds were unimpressed." The supply drop has been reclassified as a "meteorological probe." Front 07 has been asked to make do with less.',
		cycle: 'Cycle 2150',
		classification: 'Approved',
		thumbnail: 'square',
		timestamp: '11:49 OST',
		author: 'Deployment Logistics Corps (trajectory dispute division)',
		refId: 'OCD-2150-2S63',
		source: 'handwritten',
	},
	{
		id: 63,
		category: 'Command Bulletin',
		headline: 'Orbital Command Updates Official Definition Of "Victory" To Include "Not Losing As Fast"',
		snippet: 'The Historical Accuracy Bureau has published a revised definition of military victory that now encompasses "not losing as quickly as projected," "maintaining a geometrically defensible position for at least several minutes," and "achieving a Tower survival rate above the statistical noise floor." "Under the new definition, we are winning approximately half the time," Command announced. "The other half is still under review."',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
		timestamp: '09:26 OST',
		author: 'Chief of Retroactive Justification Díaz',
		refId: 'OCD-2151-0T45',
		source: 'handwritten',
	},
	{
		id: 64,
		category: 'Historical Note',
		headline: 'Archaeological Dig Uncovers Ancient Shape-Human Peace Treaty From Pre-War Era, Treaty Is A Doodle',
		snippet: 'An excavation near the original Orbital Command foundation has uncovered what appears to be a pre-war peace agreement between Flatland settlers and the native shapes. Analysis reveals the "treaty" consists of a crudely drawn human figure shaking what might be a triangle. "We are not sure this is legally binding on either side," Chief Archivist Müller noted. "Also the triangle is smiling, which triangles cannot do." The treaty has been framed and hung in the lobby.',
		cycle: 'Cycle 2144',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '17:15 OST',
		author: 'Chief Archivist Müller, Historical Accuracy Bureau',
		refId: 'OCD-2144-3U08',
		source: 'handwritten',
	},
	{
		id: 65,
		category: 'Equipment Advisory',
		headline: 'Alloy Refinement Process Now Includes Step Where Technician Says "This Will Probably Work"',
		snippet: 'Updated Forge Assembly protocols mandate that all Alloy refinement batches include a verbal confidence declaration from the overseeing technician. "The step itself has no measurable impact on Alloy quality," Foreman Nakamura confirmed. "But the ritual is important." The most common declaration — "This will probably work" — has been associated with a 2.3% improvement in structural integrity. Sarcastic declarations have been banned after an incident in Bay 4.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'hexagon',
		timestamp: '15:09 OST',
		author: 'Foreman Nakamura, Forge Assembly Division',
		refId: 'OCD-2151-8V71',
		source: 'handwritten',
	},
	{
		id: 66,
		category: 'Field Report',
		headline: 'Tower Mysteriously Survives Every Wave While Playing Dead, Analysts Unsure If Intentional',
		snippet: 'Tower FLD-3390 on Front 03 has survived 47 consecutive waves by ceasing all fire and remaining completely motionless. "The shapes appear to ignore it entirely," the field report states. "We are not sure if this is a bug, a strategy, or the Tower having an existential crisis." Research Deck 7 has proposed studying the Tower without disturbing it. Command has designated the tactic "passive persistence" and is considering adding it to the training manual.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '20:52 OST',
		author: 'Field Observer (name withheld at observer\'s request)',
		refId: 'OCD-2151-3W19',
		source: 'handwritten',
	},
	{
		id: 67,
		category: 'Bureaucratic Notice',
		headline: 'Department Of Redundancy Department Opens Second Office To Handle Redundancy Inquiries',
		snippet: 'The newly formed Department of Redundancy Department (DRD) has opened a second office to process inquiries about its own existence. "We received so many questions about whether we are redundant that we needed a redundant department to handle them," explained Acting Director Hayes. Both offices perform identical functions. Both claim the other is unnecessary. Personnel have been advised to file complaints with either office, or both, or neither.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '14:23 OST',
		author: 'Acting Director Hayes, Department of Redundancy Department',
		refId: 'OCD-2152-5X11',
		source: 'handwritten',
	},
	{
		id: 68,
		category: 'Diplomatic Cable',
		headline: 'Shapes Respond To Diplomatic Overture By Simply Leaving, Diplomats Declare Victory',
		snippet: 'In an unprecedented diplomatic development, a delegation of hostile shapes on Front 01 responded to an overture from the Office of Geometric Relations by turning approximately 180 degrees and moving away. "They have withdrawn in the face of our diplomatic pressure," Deputy Envoy Tanaka declared. Military analysts note the shapes were already moving in that direction and had been doing so for three hours before the diplomatic team arrived. The Office has declared the encounter a "negotiated disengagement."',
		cycle: 'Cycle 2151',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '12:18 OST',
		author: 'Office of Geometric Relations (victory declaration sub-unit)',
		refId: 'OCD-2151-6Y44',
		source: 'handwritten',
	},
	{
		id: 69,
		category: 'Scientific Breakthrough',
		headline: 'Research Deck 7 Accidentally Creates New Shape, Immediately Classifies It As Hostile',
		snippet: 'A geometric synthesis experiment in Research Deck 7 has inadvertently produced a new shape that does not correspond to any known Flatland entity. "We made it by accident and it immediately tried to escape containment," Dr. Okonkwo reported. "Per protocol, we have classified it as hostile." The new shape — tentatively designated "The Accident" — is currently contained in Lab 7-C. Research Deck has requested funding to make another one, for comparison.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '22:04 OST',
		author: 'Dr. Okonkwo, Research Deck 7 (accidental creation division)',
		refId: 'OCD-2152-8Z77',
		source: 'handwritten',
	},
	{
		id: 70,
		category: 'Personnel Update',
		headline: 'Entire Morale Bureau Calls In Sick On Same Day, Morale Immediately Improves',
		snippet: 'All 34 employees of the Morale Bureau reported sick on Cycle 2151 Day 87, citing "emotional exhaustion from monitoring everyone else\'s emotional exhaustion." With no Morale officers present to measure it, morale across Orbital Command reportedly improved by 41%. "We have no way to verify this since the people who measure it are not here," a Command spokesperson noted. The Bureau returned the following day. Morale dropped back to baseline within hours.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '10:04 OST',
		author: 'Automated attendance system',
		refId: 'OCD-2151-1A80',
		source: 'handwritten',
	},
	{
		id: 71,
		category: 'Threat Assessment',
		headline: 'Intelligence Suggests Shapes May Have Access To Our Deployment Schedule, Schedule Is Posted On Public Terminal',
		snippet: 'A threat analysis by Communications Oversight Panel has identified a possible security breach: the Tower deployment schedule is displayed on an unsecured public terminal in the Orbital Command lobby. "Anyone could theoretically see it," the report states, "including shapes, if shapes visited the lobby, which they have not, but technically could." The terminal has been covered with a piece of paper marked "Classified — Do Not Look." The paper has been there for three cycles.',
		cycle: 'Cycle 2150',
		classification: 'Sanitized',
		thumbnail: 'warning',
		timestamp: '11:31 OST',
		author: 'Communications Oversight Panel (retrospectively alarmed)',
		refId: 'OCD-2150-9B35',
		source: 'handwritten',
	},
	{
		id: 72,
		category: 'Budget Review',
		headline: 'Quarterly Report Concludes War Is Costing Money, Finance Division Discovers This Is Expected',
		snippet: 'After an exhaustive fiscal review, Finance Division has reached the conclusion that the Flatland conflict costs money to prosecute. "We had hoped the shapes would at some point begin funding themselves," the report states, "but this has not materialized." The Division recommends continued expenditure until either the shapes are defeated or Accounting figures out how to make war fiscally self-sustaining. Neither outcome is considered likely in the current fiscal cycle.',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '16:42 OST',
		author: 'Finance Division (disappointed but not surprised)',
		refId: 'OCD-2151-7C28',
		source: 'handwritten',
	},
	{
		id: 73,
		category: 'Equipment Advisory',
		headline: 'Tower Self-Destruct Mechanism Found To Be Triggered By Strongly Worded Criticism',
		snippet: 'An investigation into a cluster of unexplained Tower detonations on Front 03 has revealed the Mk-V fire control system interprets harsh language from Orbital Command as a self-destruct command. "The Towers are apparently quite sensitive," the engineering report notes. Command has issued a directive requiring all Tower communications to include at least one compliment. "You are doing great, Tower. Please continue to exist." is the current recommended opening.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '18:55 OST',
		author: 'Forge Assembly Division Engineering Corps',
		refId: 'OCD-2151-4D93',
		source: 'handwritten',
	},
	{
		id: 74,
		category: 'Frontline Report',
		headline: 'Shapes Begin Avoiding Front 07 After Tower Plays Recorded Sound Of Bureaucracy Meeting',
		snippet: 'In a desperate defensive measure, Tower FLD-5581 on Front 07 broadcast a 14-hour recording of a Procurement budget reconciliation meeting at maximum volume. Within minutes, enemy shape activity in the sector dropped by 78%. "They appear to find bureaucratic procedure as unbearable as we do," noted Lt.-Analyst Chen. Orbital Command has classified the recording as a "sonic deterrent" and is compiling a playlist of similar audio assets, including "Finance Responds To Audit Findings, Part 1 Through 7."',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '14:37 OST',
		author: 'Lt.-Analyst Chen (with reluctant admiration)',
		refId: 'OCD-2152-2E56',
		source: 'handwritten',
	},
	{
		id: 75,
		category: 'Command Bulletin',
		headline: 'Orbital Command Declares Cycle 2152 "The Cycle Of Decisive Outcomes," Refuses To Specify Which Outcomes',
		snippet: 'In a rousing address, Orbital Command has designated Cycle 2152 as "The Cycle of Decisive Outcomes." When pressed for details on what outcomes would be considered decisive, a Command spokesperson stated that "the decisiveness of outcomes will be evaluated retroactively based on which outcomes occur." The address concluded with a reminder that optimism is mandatory. Several outcomes have already occurred. None have been deemed sufficiently decisive.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '08:00 OST',
		author: 'Orbital Command Strategic Communications',
		refId: 'OCD-2152-1F03',
		source: 'handwritten',
	},
	{
		id: 76,
		category: 'R&D Briefing',
		headline: 'Research Team Spends Entire Cycle Determining Whether Tower Explosion Counts As "Data" Or "Loss"',
		snippet: 'A Research Deck 7 working group has spent the entirety of Cycle 2151 attempting to categorize a single Tower detonation as either "actionable combat data" (which would make it a research success) or "equipment loss" (which would make it a deployment failure). The 38-page final report concludes that it is "contextually both." Procurement has filed it under "data." Finance has filed it under "loss." The Tower\'s opinion was not solicited.',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '17:49 OST',
		author: 'Research Deck 7 (categorization working group)',
		refId: 'OCD-2151-0G61',
		source: 'handwritten',
	},
	{
		id: 77,
		category: 'Morale Update',
		headline: 'Anonymous Survey Finds 100% Of Personnel Would Prefer The War End, Morale Bureau Classifies Result As "Unhelpful"',
		snippet: 'An anonymous survey conducted by the Morale Bureau found that 100% of respondents expressed a preference for the Flatland conflict to conclude. "This data is technically correct but operationally useless," a Bureau spokesperson stated. The survey results have been filed under "Acknowledged But Not Actionable." A follow-up survey asking "Would you prefer the war end, or additional snack options in the cafeteria?" is currently in development.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '13:14 OST',
		author: 'Morale Bureau Survey Division',
		refId: 'OCD-2151-9H37',
		source: 'handwritten',
	},
	{
		id: 78,
		category: 'Supply Bulletin',
		headline: 'Coffee Supply On Deck 7 Runs Out, Research Output Increases By 40%',
		snippet: 'Research Deck 7 operated without coffee for 72 hours after a supply shipment was delayed by what Procurement described as "administrative congestion." During this period, research output increased by 40%, and the Orbital Institute of Applied Geometry published three papers previously stalled in peer review. Coffee has since been restored. Output has returned to normal levels. Procurement has been asked not to fix the coffee situation again but to leave it pleasingly broken.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'warning',
		timestamp: '09:22 OST',
		author: 'Research Deck 7 (caffeinated observations division)',
		refId: 'OCD-2152-3J44',
		source: 'handwritten',
	},
	{
		id: 79,
		category: 'Diplomatic Cable',
		headline: 'Shapes Issue Counter-Memo Demanding Orbital Command "Stop Dropping Towers On Us"',
		snippet: 'In a historic first, hostile shapes on Front 01 have issued what analysts describe as a "counter-memo" — a geometric formation that, when translated, loosely demands that Orbital Command cease dropping Towers on their positions. "The shapes have filed a complaint," a stunned Deputy Envoy Tanaka reported. "We are now in a bureaucratic engagement." Command has responded by placing the counter-memo in the standard review queue. Estimated response time: 4-6 cycles.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'hexagon',
		timestamp: '21:08 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2152-6K13',
		source: 'handwritten',
	},
	{
		id: 80,
		category: 'Procurement Log',
		headline: 'Procurement Accidentally Liquidates Itself, Reforms Two Hours Later As "Strategic Asset Reallocation"',
		snippet: 'A routine departmental audit triggered an automated liquidation protocol in Procurement\'s own records system, briefly dissolving the entire department. "For approximately two hours, Procurement did not exist," a Command spokesperson confirmed. "Paperwork continued to be processed by pure inertia." The department was reformed under the title "Strategic Asset Reallocation Division" with identical staff, identical offices, and identical refusal to answer questions.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '15:33 OST',
		author: 'Strategic Asset Reallocation Division (formerly Procurement)',
		refId: 'OCD-2152-4L76',
		source: 'handwritten',
	},
	{
		id: 81,
		category: 'Field Report',
		headline: 'Tower Achieves 0.00% Accuracy Rating, Somehow Still Considered "Morale Positive"',
		snippet: 'Tower FLD-6671 deployed on Front 12 has fired 3,402 rounds without hitting a single shape. Despite this, the Morale Bureau has classified the Tower as "morale positive" because "the firing sounds are quite reassuring." The Tower continues to operate at full capacity. Shapes in the sector have reportedly stopped bothering to dodge. "They know," a field observer reported. "They definitely know."',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '05:18 OST',
		author: 'Morale Compliance Inspector Thorne',
		refId: 'OCD-2151-5M02',
		source: 'handwritten',
	},
	{
		id: 82,
		category: 'Bureaucratic Notice',
		headline: 'Orbital Command Introduces "Pre-Complaint Form" That Must Be Filed Before Filing A Complaint',
		snippet: 'The Bureau of Statistical Convenience has introduced Form OCD-7P (Pre-Complaint Declaration), which personnel must complete before submitting an actual complaint via Form OCD-7Q. "This ensures complaints are made with proper prior consideration," the directive states. Early feedback has been submitted via complaints about the pre-complaint process. These complaints require Form OCD-7P-1 (Complaint About Pre-Complaint Process), which requires...',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '10:41 OST',
		author: 'Bureau of Statistical Convenience (Forms Division, recursive sub-unit)',
		refId: 'OCD-2152-7N85',
		source: 'handwritten',
	},
	{
		id: 83,
		category: 'Threat Assessment',
		headline: 'Pentagon Achieves Self-Awareness For 0.7 Seconds, Uses Time To File Complaint About Existence',
		snippet: 'Sensors on Front 03 captured a brief spike in neural-analog activity from a pentagonal entity, lasting approximately 0.7 seconds. "In that time, the pentagon appeared to become aware of its own existence and immediately register dissatisfaction with it," Dr. Okonkwo reported. The shape then resumed being a shape. Orbital Command has classified self-aware shapes as a Priority 1 threat. "A shape that knows it is a shape is inherently more dangerous than a shape that does not," the classification states.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '19:37 OST',
		author: 'Dr. Okonkwo, Research Deck 7 (existential geometry division)',
		refId: 'OCD-2152-8P29',
		source: 'handwritten',
	},
	{
		id: 84,
		category: 'Command Bulletin',
		headline: 'Orbital Command Admits War May Have "Tangential Objectives," Refuses To Name Them',
		snippet: 'In an unusually candid moment during a press briefing, an Orbital Command spokesperson acknowledged the Flatland conflict may have "tangential objectives" beyond the stated goal of shape elimination. When asked to specify these objectives, the spokesperson clarified that "tangential means they are not central to the main axis of operations, which is convenient because it means we do not have to tell you what they are." The briefing concluded. Further briefings have been scheduled. The schedules are classified.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
		timestamp: '11:09 OST',
		author: 'Orbital Command Press Office',
		refId: 'OCD-2152-9Q55',
		source: 'handwritten',
	},
	{
		id: 85,
		category: 'Historical Revision',
		headline: 'Historical Accuracy Bureau Updates All Maps To Remove Fronts Where Towers Were Lost',
		snippet: 'Following standard post-loss protocol, the Historical Accuracy Bureau has updated official Flatland maps to remove Fronts 04, 09, and 14 — all locations where Tower loss rates exceeded the acceptable margin. "If the Front is not on the map, the losses did not occur there," Chief of Retroactive Justification Díaz explained. The shapes occupying those Fronts have not been informed of their cartographic nonexistence. Several have reportedly continued to exist anyway, which the Bureau describes as "administratively inconvenient."',
		cycle: 'Cycle 2151',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '16:28 OST',
		author: 'Chief of Retroactive Justification Díaz',
		refId: 'OCD-2151-2R14',
		source: 'handwritten',
	},
	{
		id: 86,
		category: 'Equipment Advisory',
		headline: 'Mk-VII Tower Features "Optimistic Targeting" Mode That Assumes Shapes Will Move Into Bullets',
		snippet: 'The newly deployed Mk-VII Tower includes a firing mode designated "Optimistic Targeting," which fires rounds at coordinates where no shapes currently are, under the assumption that shapes will eventually arrive there. "It is a bet on the future," the technical manual explains. Field tests show a 2.3% hit rate, which Research Deck 7 describes as "exceeding pessimistic projections." Procurement has ordered 200,000 units. "We believe in the shapes\' willingness to cooperate," a spokesperson added.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '14:52 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2152-5S38',
		source: 'handwritten',
	},
	{
		id: 87,
		category: 'Morale Update',
		headline: 'Personnel Retention Taskforce Renamed "Personnel Persistence Taskforce" After Retention Proves Unlikely',
		snippet: 'The Personnel Retention Taskforce has officially rebranded as the Personnel Persistence Taskforce following a quarterly review that revealed retention was "statistically aspirational." "We cannot retain personnel, but we can persist in trying to retain them," the rebranding memo states. The Taskforce\'s new motto — "Still Here, Mostly" — has been printed on morale posters across Orbital Command. The posters were designed by an intern who has since left.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '09:15 OST',
		author: 'Personnel Persistence Taskforce (formerly Personnel Retention Taskforce)',
		refId: 'OCD-2152-1T67',
		source: 'handwritten',
	},
	{
		id: 88,
		category: 'Scientific Breakthrough',
		headline: 'Mathematicians Prove War Is Geometrically Unwinnable, Finance Counters That It Is Fiscally Sustainable',
		snippet: 'A joint paper from the Orbital Institute of Applied Geometry and the Bureau of Statistical Convenience mathematically demonstrates the Flatland conflict cannot be won under current parameters. Finance Division issued an immediate rebuttal: "The war may be geometrically unwinnable, but it is fiscally sustainable at current expenditure levels, which is the metric that matters." The mathematicians have been invited to refile their findings as a budget proposal.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '20:43 OST',
		author: 'Orbital Institute of Applied Geometry & Finance Division (joint, reluctantly)',
		refId: 'OCD-2152-6U92',
		source: 'handwritten',
	},
	{
		id: 89,
		category: 'Procurement Log',
		headline: 'Procurement Finds Warehouse Of Unsent Diplomatic Cables, Shapes Were Never Actually Informed Of War',
		snippet: 'An inventory sweep of Communications Relay 14 uncovered 847 unsent diplomatic cables dating back to Cycle 2139. The cables contain formal declarations of conflict that were never transmitted to the shapes. "The shapes may not know there is a war," a Procurement analyst stated. "They may think this is just how we say hello." Orbital Command has classified the discovery. The war continues. The shapes continue to not be informed.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '22:17 OST',
		author: 'Senior Procurement Specialist Andersson',
		refId: 'OCD-2152-3V48',
		source: 'handwritten',
	},
	{
		id: 90,
		category: 'Frontline Report',
		headline: 'Lone Triangle Approaches Tower Bearing What Appears To Be White Flag, Tactical Analysis Ongoing',
		snippet: 'A single triangular entity on Front 01 has been observed approaching Tower FLD-2287 carrying a small white polygon on what might be described as a stick. "We are not sure if this is a surrender, a trap, or performance art," Lt.-Analyst Chen reported. The Tactical Doctrine Review Board has convened an emergency session. Three sub-committees have been formed. The triangle continues to approach at a steady pace. The Tower has been instructed to "wait and see." The triangle is now 12 meters away.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '08:56 OST',
		author: 'Lt.-Analyst Chen (ongoing observation)',
		refId: 'OCD-2152-4W15',
		source: 'handwritten',
	},
	{
		id: 91,
		category: 'Budget Review',
		headline: 'War Fund Temporarily Replaced With IOU After Accounting Miscounts Zeroes',
		snippet: 'Finance Division has confirmed that the Cycle 2152 War Expenditure Fund was briefly converted to a handwritten IOU after a data entry error removed several zeroes from the balance sheet. "The fund technically existed only as a piece of paper with \'We Owe You One War\' written on it," Lead Auditor Popescu confirmed. The error was corrected within six hours. The IOU has been framed and displayed in the Finance Division lobby as "a reminder of fiscal humility."',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '17:35 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2152-9X82',
		source: 'handwritten',
	},
	{
		id: 92,
		category: 'Personnel Update',
		headline: 'Orbital Command Introduces "Vertical Career Advancement" Which Is Just Being Promoted To A Higher Floor',
		snippet: 'The Personnel Persistence Taskforce has unveiled a new career development framework: Vertical Career Advancement (VCA). Personnel who receive VCA are relocated to a higher floor of Orbital Command with the same job title and responsibilities. "The view is better, which is the promotion," the memo explains. Three personnel have been vertically advanced to Deck 14. Two have reported improved morale. One has reported vertigo. All three still do the same job.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '12:22 OST',
		author: 'Personnel Persistence Taskforce',
		refId: 'OCD-2152-7Y50',
		source: 'handwritten',
	},
	{
		id: 93,
		category: 'R&D Briefing',
		headline: 'Experimental Tower Powered Entirely By Sunk Cost Fallacy Achieves Record Runtime',
		snippet: 'Research Deck 7 has deployed an experimental Tower powered not by Alloy but by the accumulated psychological weight of resources already invested in its development. "We have spent so much on this Tower that it simply cannot be allowed to fail," Dr. Okonkwo explained. The Tower has achieved a record 217-hour operational runtime. "It runs on the fear of admitting we wasted the budget," a technician added. Procurement has doubled funding for the project.',
		cycle: 'Cycle 2152',
		classification: 'Sanitized',
		thumbnail: 'radar',
		timestamp: '15:04 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2152-2Z39',
		source: 'handwritten',
	},
	{
		id: 94,
		category: 'Command Bulletin',
		headline: 'Orbital Command Denies Existence Of "War Fatigue," Claims Personnel Are Simply "Strategically Resting"',
		snippet: 'In response to growing reports of "war fatigue" among Orbital Command personnel, a Command spokesperson has clarified that no such condition exists. "What has been observed is Strategic Restfulness — a fully authorized operational posture," the statement reads. Personnel found resting strategically are encouraged to continue. Personnel found resting non-strategically will be enrolled in Strategic Restfulness Training. The distinction between the two remains classified.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
		timestamp: '18:11 OST',
		author: 'Orbital Command Strategic Communications',
		refId: 'OCD-2152-5A67',
		source: 'handwritten',
	},
	{
		id: 95,
		category: 'Field Report',
		headline: 'Tower Develops Preference For Dramatic Pause Before Firing, Shapes Reportedly Unsettled',
		snippet: 'Tower FLD-7742 on Front 03 has begun inserting a 1.5-second pause before each shot, during which it rotates its barrel slightly and emits what field observers describe as "an almost theatrical hum." Shapes in the sector have reportedly altered their approach patterns in response. "They seem confused by the dramatic timing," a field report notes. "It is not tactically optimal, but it is artistically compelling." Research Deck 7 has proposed studying the Tower\'s "performance combat" style.',
		cycle: 'Cycle 2152',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '21:29 OST',
		author: 'Field Observer, Front 03',
		refId: 'OCD-2152-8B13',
		source: 'handwritten',
	},
	{
		id: 96,
		category: 'Threat Assessment',
		headline: 'New Shape Variant Appears To Be Waving, Orbital Command Unsure If Friendly Or Taunting',
		snippet: 'A newly observed shape variant on Front 12 has been recorded performing a rhythmic back-and-forth oscillation that analysts describe as "indistinguishable from waving." The Committee for Shape-Related Incidents is divided: the Optimism Sub-Committee classifies it as a friendly gesture, while the Threat Sub-Committee believes it is mockery. "We will not know until it is closer, at which point it may be too late," the interim report states. The shape is slowly approaching.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '07:44 OST',
		author: 'Sub-Director Fletcher, Committee for Shape-Related Incidents',
		refId: 'OCD-2152-1C99',
		source: 'handwritten',
	},
	{
		id: 97,
		category: 'Diplomatic Cable',
		headline: 'Office Of Geometric Relations Proposes Renaming Shapes As "Geometric Citizens," Shapes Do Not Respond',
		snippet: 'In a bid to reframe the conflict, the Office of Geometric Relations has proposed officially reclassifying hostile shapes as "Geometric Citizens (Provisional)." "Language shapes perception," Deputy Envoy Tanaka argued. "If we call them citizens, perhaps they will act like citizens." The proposal has been forwarded to 14 departments for review. The shapes have not responded to the proposal, as they cannot read and were not sent a copy.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'hexagon',
		timestamp: '13:58 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Relations',
		refId: 'OCD-2152-6D31',
		source: 'handwritten',
	},
	{
		id: 98,
		category: 'Supply Bulletin',
		headline: 'Emergency Ration Pack Mislabelled "Morale Supplement," Personnel Report Feeling "Technically Better"',
		snippet: 'A supply shipment intended for Front 07 contained emergency ration packs mislabelled as "Morale Supplement — Strawberry Flavoured." Personnel who consumed the supplements reported feeling "technically better, in the sense that not being hungry is technically an improvement in morale." The Morale Bureau has claimed credit for the 0.7% morale increase. Procurement has been asked to mislabel additional supplies.',
		cycle: 'Cycle 2151',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '19:46 OST',
		author: 'Morale Bureau (opportunistic credit division)',
		refId: 'OCD-2151-3E78',
		source: 'handwritten',
	},
	{
		id: 99,
		category: 'Scientific Breakthrough',
		headline: 'Research Conclusively Proves Shapes Do Not Enjoy Being Shot, Finding Described As "Tactically Useful"',
		snippet: 'After 14 cycles of observation, the Orbital Institute of Behavioral Geometry has published definitive research confirming that shapes do not enjoy being shot. "Previous studies were inconclusive due to the shapes\' limited emotional expressiveness," Dr. de Souza explained. "But the evidence is now overwhelming: they would prefer not to be shot." The finding has been incorporated into tactical doctrine. Towers will continue to shoot shapes, which the shapes will continue to not enjoy.',
		cycle: 'Cycle 2152',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '10:15 OST',
		author: 'Dr. de Souza, Orbital Institute of Behavioral Geometry',
		refId: 'OCD-2152-0F44',
		source: 'handwritten',
	},
	{
		id: 100,
		category: 'Command Bulletin',
		headline: 'Orbital Command Announces "Review Of The Review Process," 47 New Forms Required',
		snippet: 'In what the Bureau of Statistical Convenience is calling "a recursive administrative milestone," Orbital Command has initiated a comprehensive review of the review process itself. The initiative requires 47 new forms, including OCD-7R (Intent to Review), OCD-7S (Review of Intent to Review), and OCD-7T (Meta-Review Cover Sheet). "We estimate the review of the review process will take approximately three cycles," the announcement states. "At which point we will review the review of the review process." Personnel have been advised to keep their calendars clear through Cycle 2155.',
		cycle: 'Cycle 2152',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '16:00 OST',
		author: 'Orbital Command & Bureau of Statistical Convenience (joint meta-administrative taskforce)',
		refId: 'OCD-2152-9G77',
		source: 'handwritten',
	},

	// ========================================================================
	// NEW articles (ids 101–120)
	// ========================================================================

	{
		id: 101,
		category: 'Threat Assessment',
		headline: 'Shapes Reportedly "Disappointed" In Latest Tower Deployment, According To Translated Vibrations',
		snippet: 'The Orbital Institute of Behavioral Geometry has translated a series of low-frequency vibrations emitted by shapes on Front 03. The rough translation reads: "This again? We expected better." Dr. de Souza described the findings as "a blow to institutional pride." Orbital Command has ordered the translation classified and has commissioned a new Tower variant specifically designed to be less disappointing. Early prototypes have been described by the shapes as "marginally less predictable," which Command considers a win.',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '14:22 OST',
		author: 'Dr. de Souza, Orbital Institute of Behavioral Geometry',
		refId: 'OCD-2153-1H44',
		source: 'handwritten',
	},
	{
		id: 102,
		category: 'Procurement Log',
		headline: 'Procurement Orders 12,000 Towers Without Realising They Require A Front To Deploy To',
		snippet: 'An automated procurement order placed during a server migration has resulted in the manufacture of 12,000 Towers with no designated deployment Front. "The Towers are fully functional and ready for action," a Procurement spokesperson confirmed. "They simply have nowhere to go." The Towers are currently stored in Silo 17, where they have reportedly begun communicating with each other via low-frequency hums. Research Deck 7 has requested permission to study "Tower social behaviour." Permission is pending review.',
		cycle: 'Cycle 2153',
		classification: 'Sanitized',
		thumbnail: 'tower',
		timestamp: '10:07 OST',
		author: 'Senior Procurement Specialist Andersson',
		refId: 'OCD-2153-2T53',
		source: 'handwritten',
	},
	{
		id: 103,
		category: 'Field Report',
		headline: 'Tower Survives Wave 100 By Explaining Its Existence To Shapes, Shapes Reportedly "Uncomfortable"',
		snippet: 'Tower FLD-9034 on Front 12 survived an unprecedented 100 waves by emitting what field observers describe as "a continuous stream of existential justification" — a low-frequency broadcast explaining why the Tower exists, what its purpose is, and why the shapes should perhaps reconsider their approach. "The shapes seemed genuinely unsettled by the Tower\'s self-awareness," the field report states. "Several turned around. Others slowed to a contemplative pace." Research Deck 7 has proposed equipping all Towers with "philosophical defence modules."',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '21:44 OST',
		author: 'Field Observer, Front 12 (philosophically moved)',
		refId: 'OCD-2153-3U29',
		source: 'handwritten',
	},
	{
		id: 104,
		category: 'Budget Review',
		headline: 'Finance Division Discovers War Is 400% Over Budget, Reclassifies Overrun As "Strategic Ambition"',
		snippet: 'A quarterly audit has revealed the Flatland conflict has exceeded its original budget by approximately 400%. Finance Division has addressed this by redefining the budget itself. "The original budget was a suggestion," Lead Auditor Popescu explained. "The actual budget is whatever we spend. This is called Strategic Fiscal Ambition." The redefinition has been approved by three committees. The budget is now technically balanced, provided you accept the premise that budgets are aspirational documents rather than constraints.',
		cycle: 'Cycle 2153',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '15:58 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2153-4V81',
		source: 'handwritten',
	},
	{
		id: 105,
		category: 'R&D Briefing',
		headline: 'Experimental Tower Fires Encouragement Instead Of Projectiles, Shapes Stop To Listen',
		snippet: 'Research Deck 7 has deployed a Tower variant that replaces standard ammunition with recorded messages of encouragement. Early results are mixed: several shapes paused their advance to absorb the positive messaging, while others accelerated as if offended. "The shapes have complex emotional responses to kindness," Dr. Okonkwo reported. "Some are moved. Others are furious." The Tower\'s current message library includes "You are more than your angles" and "Being a shape is valid." Procurement has pre-ordered audio equipment for 800 additional Towers.',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'radar',
		timestamp: '09:31 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2153-5W17',
		source: 'handwritten',
	},
	{
		id: 106,
		category: 'Command Bulletin',
		headline: 'Orbital Command Issues Statement Clarifying That "War" Is A Strong Word For What Is Happening',
		snippet: 'In a carefully worded press release, Orbital Command has clarified that the term "war" may overstate the nature of the ongoing conflict with Flatland shapes. "We prefer \'Extended Geometric Disagreement,\'" the statement reads. "Or \'Protracted Boundary Discussion.\' The shapes have not agreed to this terminology, but they have not disagreed either, which is technically consent." Personnel are advised to update their vocabulary accordingly. The Office of Geometric Relations has been renamed the Office of Geometric Discourse.',
		cycle: 'Cycle 2153',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '11:15 OST',
		author: 'Orbital Command Press Office',
		refId: 'OCD-2153-6X42',
		source: 'handwritten',
	},
	{
		id: 107,
		category: 'Personnel Update',
		headline: 'Employee Of The Cycle Awarded To Tower That Did Absolutely Nothing But Survived Longer Than Everyone',
		snippet: 'The Personnel Persistence Taskforce has awarded Employee of the Cycle to Tower FLD-0000, which was deployed to Front 01, immediately powered down all systems, and sat motionless for 312 waves. "It contributed nothing," the commendation reads. "It also cost nothing in ammunition, required no repairs, and outlasted every active Tower in the sector. That is efficiency." The Tower has been designated a "Passive Persistence Model" and will be studied for insights into strategic inaction.',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '13:09 OST',
		author: 'Personnel Persistence Taskforce',
		refId: 'OCD-2153-7Y36',
		source: 'handwritten',
	},
	{
		id: 108,
		category: 'Historical Note',
		headline: 'Archives Discover War Has Been Running 47 Cycles Longer Than Anyone Remembered',
		snippet: 'A routine Archives audit has uncovered 47 cycles of Flatland conflict documentation that no living personnel recall experiencing. "The records exist, the deployments occurred, the Towers fell," Chief Archivist Müller stated. "We simply have no memory of any of it." Orbital Command has classified the missing cycles as "Temporal Administrative Gap 1 through 47." Research Deck 7 has proposed studying whether time itself can be misfiled. The proposal has been misfiled.',
		cycle: 'Cycle 2153',
		classification: 'Sanitized',
		thumbnail: 'classified',
		timestamp: '19:43 OST',
		author: 'Chief Archivist Müller, Historical Accuracy Bureau',
		refId: 'OCD-2153-8Z99',
		source: 'handwritten',
	},
	{
		id: 109,
		category: 'Diplomatic Cable',
		headline: 'Office Of Geometric Discourse Invites Shapes To "Town Hall," Shapes Form A Rectangle With Chairs',
		snippet: 'The newly renamed Office of Geometric Discourse has extended an invitation to hostile shapes for a "Town Hall" meeting to discuss mutual concerns. In response, shapes on Front 01 arranged themselves into a rectangular formation with what analysts describe as "seating." "They appear to have set up chairs," a stunned Deputy Envoy Tanaka reported. "We are now checking whether they expect refreshments." Orbital Command has dispatched a diplomatic team with coffee and a prepared PowerPoint. The shapes have not confirmed the agenda.',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'hexagon',
		timestamp: '16:28 OST',
		author: 'Deputy Envoy Tanaka, Office of Geometric Discourse',
		refId: 'OCD-2153-9A11',
		source: 'handwritten',
	},
	{
		id: 110,
		category: 'Supply Bulletin',
		headline: 'Emergency Alloy Transport Vehicle Stolen By Shapes, Later Returned With Note Saying "Thank You"',
		snippet: 'An Alloy transport vehicle en route to Front 07 was intercepted by a coordinated shape formation and temporarily removed from Orbital Command custody. The vehicle was recovered six hours later — undamaged, fully fuelled, and containing a geometric arrangement that analysts have translated as "Thank you. The Alloy was delicious. We will not forget this." Orbital Command has classified the incident and initiated a review of shape dietary requirements. "We did not know they ate Alloy," a Command spokesperson admitted. "This changes several assumptions."',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
		timestamp: '22:51 OST',
		author: 'Deployment Logistics Corps (considerably unnerved)',
		refId: 'OCD-2153-0B77',
		source: 'handwritten',
	},
	{
		id: 111,
		category: 'Scientific Breakthrough',
		headline: 'Research Deck 7 Discovers Shapes Are Capable Of Boredom, Classifies Boredom As Weaponizable',
		snippet: 'A long-term observation study has confirmed that shapes exhibit behaviour consistent with boredom when confronted with repetitive Tower firing patterns. "After approximately 40 minutes of identical engagement, shapes begin moving more slowly, as if questioning the point of it all," Dr. Okonkwo reported. Research Deck 7 has classified boredom as a "Psychological Operations Vector" and is developing a Tower variant that fires exactly the same pattern indefinitely. "If we can make the war sufficiently tedious," the proposal states, "the shapes may simply leave."',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
		timestamp: '10:44 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2153-1C62',
		source: 'handwritten',
	},
	{
		id: 112,
		category: 'Morale Update',
		headline: 'Morale Bureau Introduces "Pre-Approved Emotional State" Roster, Operators May Select From Three Options',
		snippet: 'The Morale Bureau has streamlined emotional wellness by introducing a roster of three pre-approved emotional states: Cautiously Optimistic, Functionally Neutral, and Professionally Resigned. "Spontaneous emotions create administrative unpredictability," the directive explains. Personnel are required to log their selected state on Form OCD-7U (Emotional State Declaration) at the start of each shift. Early compliance has been measured at 17%. The remaining 83% of personnel have been classified as "Emotionally Non-Standard" and enrolled in Supplemental Emotional Standardisation.',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
		timestamp: '08:15 OST',
		author: 'Morale Bureau Standardisation Division',
		refId: 'OCD-2153-2D38',
		source: 'handwritten',
	},
	{
		id: 113,
		category: 'Equipment Advisory',
		headline: 'Tower Mk-VIII Features "Aggressive Optimism" Protocol That Assumes Victory Has Already Occurred',
		snippet: 'The newly deployed Mk-VIII Tower includes an "Aggressive Optimism" protocol that operates under the assumption that all shapes have already been defeated. "The Tower fires celebratory rounds because in its operational reality, the war is over and we won," the technical manual explains. Field tests show the Tower firing into empty space approximately 94% of the time. The remaining 6% of shots accidentally hit shapes, which the Tower\'s logs record as "confused post-victory participants." Procurement has ordered 500,000 units.',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
		timestamp: '14:33 OST',
		author: 'Dr. Okonkwo, Research Deck 7',
		refId: 'OCD-2153-3E97',
		source: 'handwritten',
	},
	{
		id: 114,
		category: 'Frontline Report',
		headline: 'Pentagon-Variant Shape Stops Mid-Advance, Appears To Be Doing Math',
		snippet: 'Sensors on Front 12 have detected a pentagon-class shape that halted its advance and began emitting rhythmic pulses that, when rendered visually, form what appears to be "extremely complicated geometry." Dr. de Souza confirmed: "It is doing math. Advanced math. Possibly better math than ours." The shape has been stationary for six hours. Orbital Command has classified the mathematics as hostile. Research Deck 7 has requested a copy of the shape\'s work. "We think it may be showing off," one analyst noted.',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
		timestamp: '18:02 OST',
		author: 'Dr. de Souza, Orbital Institute of Applied Geometry',
		refId: 'OCD-2153-4F50',
		source: 'handwritten',
	},
	{
		id: 115,
		category: 'Bureaucratic Notice',
		headline: 'Orbital Command Forms Department To Monitor Other Departments, Immediately Requires Monitoring Itself',
		snippet: 'The newly established Department of Departmental Oversight (DDO) has begun monitoring the activities of all other departments for compliance, efficiency, and philosophical alignment with Command doctrine. Within 72 hours, the DDO identified itself as requiring oversight and formed a Sub-Department of Departmental Oversight Oversight (SDDOO). The SDDOO has since identified itself as requiring oversight. Orbital Command describes the situation as "an administrative matryoshka" and has ordered all involved departments to stop looking at each other. None have complied.',
		cycle: 'Cycle 2153',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '11:49 OST',
		author: 'Department of Departmental Oversight (and its oversight)',
		refId: 'OCD-2153-5G12',
		source: 'handwritten',
	},
	{
		id: 116,
		category: 'Field Report',
		headline: 'Tower And Shape Observed In Extended Staring Contest, Neither Willing To Engage First',
		snippet: 'Tower FLD-2287 and a lone square-class shape on Front 01 have been locked in what field observers describe as "a tactical staring contest" for the past 14 hours. Neither the Tower nor the shape has made an aggressive move. "The Tower is waiting for the shape," the report states. "The shape is waiting for the Tower. We are waiting for either. Nobody is winning, but nobody is losing either, which is a kind of victory." Command has classified the engagement as "Active Non-Engagement" and is monitoring for developments.',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'square',
		timestamp: '06:37 OST',
		author: 'Field Observer, Front 01 (patient division)',
		refId: 'OCD-2153-6H84',
		source: 'handwritten',
	},
	{
		id: 117,
		category: 'Budget Review',
		headline: 'Finance Division Discovers They Have Been Funding A War On Both Sides, Considers It "Diversification"',
		snippet: 'An internal audit has revealed that for the past 11 cycles, Finance Division has inadvertently been funding both Orbital Command and — through a series of misrouted supply drops — the shapes themselves. "In our defence," Lead Auditor Popescu stated, "the shapes have shown an excellent return on investment. They are very efficient with our resources." The Division has classified the dual-funding arrangement as "Conflict Portfolio Diversification" and is considering whether to expand into other geometric conflicts. The shapes\' financial reports remain unavailable.',
		cycle: 'Cycle 2153',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
		timestamp: '20:14 OST',
		author: 'Lead Auditor Popescu, Finance Division',
		refId: 'OCD-2153-7J38',
		source: 'handwritten',
	},
	{
		id: 118,
		category: 'Command Bulletin',
		headline: 'Orbital Command Admits It Has Been Making Up Classification Levels As It Goes',
		snippet: 'In an unprecedented moment of transparency, an Orbital Command spokesperson has acknowledged that the organisation\'s system of document classification — including levels such as "Geometry Advisory," "Morale-Safe," and the recently introduced "Administratively Inconvenient" — has been improvised since Cycle 2140. "There is no master list," the spokesperson admitted. "We add a new classification whenever the existing ones feel insufficient. Several classifications have been applied to documents that do not exist, just to keep the system interesting." The admission itself has been classified as "Retrospectively Obvious."',
		cycle: 'Cycle 2153',
		classification: 'Approved',
		thumbnail: 'classified',
		timestamp: '17:06 OST',
		author: 'Orbital Command Press Office (unusually candid division)',
		refId: 'OCD-2153-8K15',
		source: 'handwritten',
	},
	{
		id: 119,
		category: 'Threat Assessment',
		headline: 'Enemy Shapes Suspected Of Reading Our News Articles After Displaying Offended Geometric Behaviour',
		snippet: 'Threat Assessment Directorate has raised concerns that hostile shapes may be intercepting and reading Flatland Wars News broadcasts. "Several shapes on Front 03 have been observed arranging themselves into formations that appear to be critical responses to articles 47, 62, and 83," Lt.-Analyst Chen reported. "They seem particularly offended by article 47, which described them as \'geometrically uncooperative.\'" Orbital Command has classified the articles as a "potential two-way communication channel." The shapes have not formally submitted a letter to the editor, but analysts believe one is geometrically implied.',
		cycle: 'Cycle 2153',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
		timestamp: '09:53 OST',
		author: 'Lt.-Analyst Chen, Threat Assessment Directorate',
		refId: 'OCD-2153-9L71',
		source: 'handwritten',
	},
	{
		id: 120,
		category: 'Command Bulletin',
		headline: 'Orbital Command Declares The Situation "In Hand," Refuses To Specify Which Hand Or Who Is Holding It',
		snippet: 'In a brief address broadcast across all Decks, Orbital Command has declared that the Flatland situation is "in hand." When pressed for details, a Command spokesperson clarified that "the hand in question is a metaphorical hand, the identity of the hand\'s owner is classified, and the hand may or may not be attached to an arm." Personnel are advised to proceed with confidence. "The situation is in a hand," the spokesperson reiterated. "Whether it is a capable hand, a trembling hand, or a hand that has already dropped several other situations is not for public discussion at this time."',
		cycle: 'Cycle 2153',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
		timestamp: '23:59 OST',
		author: 'Orbital Command Strategic Communications',
		refId: 'OCD-2153-0M01',
		source: 'handwritten',
	},
];
