export interface NewsItem {
	id: number;
	category: string;
	headline: string;
	snippet: string;
	cycle: string;
	classification: string;
	thumbnail: 'triangle' | 'tower' | 'warning' | 'radar' | 'hexagon' | 'classified' | 'square' | 'boss';
}

export const newsItems: NewsItem[] = [
	{
		id: 1,
		category: 'Frontline Report',
		headline: 'Triangles Advance With Unauthorized Confidence',
		snippet: 'Hostile triangular units have been observed moving with what analysts describe as "alarming self-assurance." Orbital Command reminds citizens that all angles below 90 degrees are to be reported immediately.',
		cycle: 'Cycle 2147',
		classification: 'Morale-Safe',
		thumbnail: 'triangle',
	},
	{
		id: 2,
		category: 'Procurement Log',
		headline: 'Procurement Denies Losing Another Blueprint',
		snippet: 'Asked to comment on the missing schematic for the Mark-IV targeting array, a Procurement spokesperson stated the document was "strategically redistributed." No further questions were permitted.',
		cycle: 'Cycle 2146',
		classification: 'Approved',
		thumbnail: 'classified',
	},
	{
		id: 3,
		category: 'Victory Bulletin',
		headline: 'Orbital Command Announces Temporary Victory Over Line Segment',
		snippet: 'In a decisive engagement lasting 0.4 seconds, a lone Tower successfully neutralized a hostile Line Segment. "This proves our doctrine works," said Command. The segment was unarmed and had no escorts.',
		cycle: 'Cycle 2146',
		classification: 'Approved',
		thumbnail: 'tower',
	},
	{
		id: 4,
		category: 'Weather Advisory',
		headline: 'Flatland Weather Report: 100% Chance of Shapes',
		snippet: 'The Flatland Meteorological Bureau forecasts continued geometric precipitation across all active Fronts. Citizens are advised to expect angles, edges, and the occasional apex threat.',
		cycle: 'Cycle 2147',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
	},
	{
		id: 5,
		category: 'R&D Briefing',
		headline: 'Research Deck Discovers Slightly More Aggressive Math',
		snippet: 'Orbital researchers have successfully recalibrated the Tower\'s combat algorithms to be "moderately more hostile." Early tests show a 2.3% increase in applied violence. Morale in the lab remains cautious.',
		cycle: 'Cycle 2145',
		classification: 'Sanitized',
		thumbnail: 'radar',
	},
	{
		id: 6,
		category: 'Labor Dispatch',
		headline: 'Forge Workers Vote To Pretend This Was The Plan',
		snippet: 'In a unanimous decision, Forge assembly crews have agreed to retroactively endorse current deployment projections. "It looks fine if you don\'t check the earlier numbers," said a spokesperson.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'hexagon',
	},
	{
		id: 7,
		category: 'Morale Update',
		headline: 'Public Morale Increased By Reclassifying Losses As Data',
		snippet: 'Following a directive from Orbital Command, all Tower losses in the last fiscal cycle have been reclassified as "voluntary field research." Early indicators show a 15% morale improvement on paper.',
		cycle: 'Cycle 2145',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
	},
	{
		id: 8,
		category: 'Sighting Report',
		headline: 'Prime Shape Seen Near Front 01, Described As "Probably Fine"',
		snippet: 'A confirmed Apex-class entity was detected on the perimeter of Front 01. Orbital Command has assured personnel that the situation is stable, provided the definition of stable remains flexible.',
		cycle: 'Cycle 2146',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
	},
	{
		id: 9,
		category: 'Supply Bulletin',
		headline: 'Alloy Rationing Declared Successful After Nobody Was Asked',
		snippet: 'Alloy distribution has been optimized based on a new predictive model that forecasts requirements significantly lower than current deployments. The model\'s creators were not available for comment.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'warning',
	},
	{
		id: 10,
		category: 'Tactical Memo',
		headline: 'New Tower Deployment Doctrine: Place It In The Middle And Hope',
		snippet: 'A revised tactical manual circulated among deployment officers recommends positioning Towers at the center of Flatland and "trusting the fire arc." The previous manual recommended the same strategy.',
		cycle: 'Cycle 2145',
		classification: 'Approved',
		thumbnail: 'tower',
	},
	{
		id: 11,
		category: 'Historical Note',
		headline: 'Archives Confirm War Started For "Administrative Convenience"',
		snippet: 'Declassified fragments from early Orbital Command records suggest the Flatland Wars may have begun due to a filing error. "The Shapes were informed of the conflict after it started," the document reads.',
		cycle: 'Cycle 2144',
		classification: 'Sanitized',
		thumbnail: 'classified',
	},
	{
		id: 12,
		category: 'Field Report',
		headline: 'Recovered Telemetry Indicates Tower Exploded Within Approved Tolerances',
		snippet: 'Engineers reviewing the latest deployment collapse confirm the Tower\'s destruction fell within acceptable performance margins. "It stopped functioning exactly as predicted," the report states approvingly.',
		cycle: 'Cycle 2146',
		classification: 'Morale-Safe',
		thumbnail: 'warning',
	},
	{
		id: 13,
		category: 'Personnel Update',
		headline: 'Orbital Command Promotes Officer Who Suggested Deploying Fewer Towers',
		snippet: 'Lieutenant-Clerk Vasquez has been awarded the Order of the Acute Angle for proposing that losing towers is "just acceleration of the research cycle." Three departments have been merged into Vasquez\'s new Division of Strategic Consolidation.',
		cycle: 'Cycle 2148',
		classification: 'Approved',
		thumbnail: 'boss',
	},
	{
		id: 14,
		category: 'Budget Review',
		headline: 'Alloy Budget Increased By Redirecting Morale Funds',
		snippet: 'The quarterly fiscal review confirms Alloy production has reached record levels after reallocating 94% of the Morale Department budget. "Sadness is free," the memo notes. The remaining 6% funds a single potted plant in the break room.',
		cycle: 'Cycle 2148',
		classification: 'Sanitized',
		thumbnail: 'hexagon',
	},
	{
		id: 15,
		category: 'Scientific Breakthrough',
		headline: 'Researchers Prove That If A Shape Cannot Be Seen, It Is Not There',
		snippet: 'The Orbital Institute of Applied Geometry has published a peer-reviewed paper concluding that shapes cease to exist when outside Tower sensor range. "This dramatically simplifies our threat model," said the lead author, who declined to visit a Front.',
		cycle: 'Cycle 2147',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
	},
	{
		id: 16,
		category: 'Diplomatic Cable',
		headline: 'Peace Talks With Hexagons Collapse After Shape Refuses To Stop Being A Shape',
		snippet: 'Diplomatic envoys report that negotiations with the Hexagon Concordat broke down when the shape delegation declined to become circles. "We presented reasonable demands and they just sat there, hexagonal," the ambassador fumed.',
		cycle: 'Cycle 2147',
		classification: 'Approved',
		thumbnail: 'hexagon',
	},
	{
		id: 17,
		category: 'Equipment Advisory',
		headline: 'Tower Targeting Computer Found To Prioritise Shapes It Finds "Aesthetically Offensive"',
		snippet: 'An internal audit of Tower combat logs reveals the Mk-V fire control system assigns higher threat scores to shapes with irregular proportions. "It is not a bug," stresses Procurement. "The machine simply has standards."',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
	},
	{
		id: 18,
		category: 'Historical Revision',
		headline: 'Archives Updated: Previous Tower Losses Now Classified As "Intentional Probes"',
		snippet: 'Orbital Command\'s Historical Accuracy Bureau has retroactively reclassified the first 2,000 Tower losses as deliberate reconnaissance missions. "We always intended to learn what happens when a Tower meets a shape at high velocity," the revised entry states.',
		cycle: 'Cycle 2148',
		classification: 'Sanitized',
		thumbnail: 'classified',
	},
	{
		id: 19,
		category: 'Geometry Advisory',
		headline: 'Hostile Squares Suspected Of Maintaining Right Angles Without Authorization',
		snippet: 'Intelligence reports confirm that enemy square units continue to display 90-degree internal angles despite multiple formal objections. Orbital Command reminds personnel that unauthorized right angles are a threat vector. Reporting channels are open.',
		cycle: 'Cycle 2149',
		classification: 'Geometry Advisory',
		thumbnail: 'square',
	},
	{
		id: 20,
		category: 'R&D Briefing',
		headline: 'Lab Accident Produces Slightly Better Results Than Intended',
		snippet: 'A containment failure in Research Deck 7 has resulted in a net improvement to Tower fire rate coefficients. "We are calling this a controlled experiment," said the lead scientist, who was not present at the time. The affected area has been cordoned off and named after someone.',
		cycle: 'Cycle 2147',
		classification: 'Sanitized',
		thumbnail: 'radar',
	},
	{
		id: 21,
		category: 'Bureaucratic Notice',
		headline: 'Enemy Shapes Refuse To Stop Spawning Despite Strongly Worded Memo',
		snippet: 'A communiqué issued to Flatland hostile forces three cycles ago demanding an immediate cessation of spawning has received no reply. Orbital Command describes this as "geometrically insubordinate" and has escalated the matter to a sub-committee.',
		cycle: 'Cycle 2149',
		classification: 'Approved',
		thumbnail: 'warning',
	},
	{
		id: 22,
		category: 'Personnel Update',
		headline: 'Analyst Promoted For Defining "Acceptable Losses" Very Broadly',
		snippet: 'Lieutenant-Analyst Marsh has been awarded the Obtuse Star for a report that classified the destruction of 94% of deployed Towers as "within the margin of expected attrition." The report has been adopted as standard doctrine. Marsh\'s formula is classified.',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'boss',
	},
	{
		id: 23,
		category: 'Diplomatic Cable',
		headline: 'Diplomatic Envoy Confirms Shapes Cannot Read',
		snippet: 'After three failed attempts to negotiate via written notice, the Office of Geometric Relations has confirmed that Flatland hostile units are non-literate. "This explains a lot," admitted the Deputy Envoy. Oral communication has also been ruled out. The war continues.',
		cycle: 'Cycle 2149',
		classification: 'Approved',
		thumbnail: 'hexagon',
	},
	{
		id: 24,
		category: 'Budget Review',
		headline: 'Emergency Fiscal Meeting Concludes Tower Should Simply Win Faster',
		snippet: 'Following a quarterly review of Alloy expenditure, Orbital Command\'s Finance Division has issued a directive recommending that Towers "resolve engagements more efficiently." No additional resources were allocated. A follow-up meeting has been scheduled to review the results of this recommendation.',
		cycle: 'Cycle 2149',
		classification: 'Sanitized',
		thumbnail: 'classified',
	},
	{
		id: 25,
		category: 'Scientific Breakthrough',
		headline: 'Researchers Confirm Shapes Are Rude On Purpose',
		snippet: 'A three-cycle study by the Orbital Institute of Behavioral Geometry has concluded that hostile shapes actively choose to be rude. "The data is unambiguous," the paper states. "They are doing it on purpose." Countermeasures are under review.',
		cycle: 'Cycle 2148',
		classification: 'Geometry Advisory',
		thumbnail: 'radar',
	},
	{
		id: 26,
		category: 'Threat Assessment',
		headline: 'Boss Shapes Found To Contain More Boss Than Previously Disclosed',
		snippet: 'Revised enemy scanning protocols have revealed that Apex-class entities carry between 40% and 300% more structural mass than initial projections. "Our original estimate assumed they would be smaller," an analyst explained. The scanning protocol has been updated. The Bosses have not.',
		cycle: 'Cycle 2149',
		classification: 'Geometry Advisory',
		thumbnail: 'boss',
	},
	{
		id: 27,
		category: 'Equipment Advisory',
		headline: 'Forge Engineers Claim Upgrades Perform Better When Given Names',
		snippet: 'An internal study conducted by the Forge Assembly Division suggests that designated equipment designations improve operator attachment and thereby perceived performance. The methodology was not peer-reviewed. Several upgrades have since been named. Results are described as "anecdotally encouraging."',
		cycle: 'Cycle 2148',
		classification: 'Morale-Safe',
		thumbnail: 'tower',
	},
	{
		id: 28,
		category: 'Frontline Report',
		headline: 'Triangles Advance In Formation Command Describes As "Technically A Shape"',
		snippet: 'Reconnaissance telemetry from Front 01 reveals hostile triangular units organizing into an aggregate formation. Analysts have declined to name the formation. "Naming it gives it power," said one. "Also, we are not sure what shape it is," said another.',
		cycle: 'Cycle 2150',
		classification: 'Geometry Advisory',
		thumbnail: 'triangle',
	},
	{
		id: 29,
		category: 'Command Bulletin',
		headline: 'Orbital Command Assures Personnel Situation Is Under Control (Classified)',
		snippet: 'In response to questions about the current state of the Flatland campaign, Orbital Command has issued a statement confirming that the situation is under control. The full statement is classified. The classification of the classification is also classified. Morale remains officially high.',
		cycle: 'Cycle 2150',
		classification: 'Morale-Safe',
		thumbnail: 'classified',
	},
	{
		id: 30,
		category: 'Victory Bulletin',
		headline: 'Tower Survives Longer Than Average, Receives No Additional Resources',
		snippet: 'A deployed Tower operating on Front 01 exceeded the operational average by 312%. Orbital Command acknowledges the performance and confirms that no supplemental Alloy, repair protocols, or commendations have been allocated. "It knows what it did," the report states. The Tower declined to comment.',
		cycle: 'Cycle 2150',
		classification: 'Approved',
		thumbnail: 'tower',
	},
];
